/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author xcamb
 */
public class App_create extends javax.swing.JFrame {

    /**
     * Creates new form App_create
     */
    public App_create() {
        initComponents();
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createEvent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        title = new javax.swing.JTextField();
        volverapp = new javax.swing.JButton();
        dateini = new com.toedter.calendar.JDateChooser();
        dateend = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bgapp_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        description.setBackground(new java.awt.Color(69, 73, 73));
        description.setColumns(20);
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setRows(5);
        description.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(description);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descripcion del evento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del evento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        createEvent.setBackground(new java.awt.Color(51, 51, 51));
        createEvent.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        createEvent.setForeground(new java.awt.Color(255, 255, 255));
        createEvent.setText("CREAR EVENTO");
        createEvent.setBorder(null);
        createEvent.setBorderPainted(false);
        createEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createEvent.setFocusPainted(false);
        createEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createEventMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createEventMouseExited(evt);
            }
        });
        jPanel1.add(createEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 180, 50));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoria del evento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 150, 30));

        category.setBackground(new java.awt.Color(60, 63, 64));
        category.setForeground(new java.awt.Color(187, 187, 186));
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Boda", "Cumpleaños", "Aniversario", "Bautizo", "Comunion", "Reunión Familiar", "Reunión Empresarial", "Graduacion" }));
        jPanel1.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 110, 150, 30));

        title.setBackground(new java.awt.Color(69, 73, 73));
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 30));

        volverapp.setBackground(new java.awt.Color(51, 51, 51));
        volverapp.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        volverapp.setForeground(new java.awt.Color(255, 255, 255));
        volverapp.setText("VOLVER");
        volverapp.setBorder(null);
        volverapp.setBorderPainted(false);
        volverapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volverapp.setFocusPainted(false);
        volverapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverappMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverappMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverappMouseExited(evt);
            }
        });
        jPanel1.add(volverapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        dateini.setBackground(new java.awt.Color(60, 63, 63));
        dateini.setForeground(new java.awt.Color(187, 187, 185));
        dateini.setToolTipText("");
        jPanel1.add(dateini, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 150, -1));
        jPanel1.add(dateend, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 150, -1));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha fin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha inicio");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        bgapp_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bgapp2.jpg"))); // NOI18N
        jPanel1.add(bgapp_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverappMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverappMouseEntered
        volverapp.setBackground(new java.awt.Color(138, 136, 136));        
    }//GEN-LAST:event_volverappMouseEntered

    private void volverappMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverappMouseExited
         volverapp.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_volverappMouseExited

    private void createEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createEventMouseEntered
        createEvent.setBackground(new java.awt.Color(138, 136, 136));
    }//GEN-LAST:event_createEventMouseEntered

    private void createEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createEventMouseExited
        createEvent.setBackground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_createEventMouseExited

    private void volverappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverappMouseClicked
       this.dispose();
       App app = new App();
       app.setVisible(true);
       app.setLocationRelativeTo(null);
    }//GEN-LAST:event_volverappMouseClicked

    private void createEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createEventMouseClicked
        String titulo = title.getText();
        String descripcion = description.getText();
        String categoria = (String) category.getSelectedItem(); 
        try
        {
                int year = dateini.getCalendar().get(Calendar.YEAR);
                int month = dateini.getCalendar().get(Calendar.MONTH)+1;
                int day = dateini.getCalendar().get(Calendar.DAY_OF_MONTH);   
                int year2 = dateend.getCalendar().get(Calendar.YEAR);
                int month2 = dateend.getCalendar().get(Calendar.MONTH)+1;
                int day2 = dateend.getCalendar().get(Calendar.DAY_OF_MONTH);    
                String fechaStr2 =year2+"-"+month2+"-"+day2;
                String fechaStr =year+"-"+month+"-"+day;
                
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-M-d");              
                System.out.println(fechaStr);
                System.out.println(fechaStr2);
                
                LocalDate fecha = LocalDate.parse(fechaStr, formatter);                
                LocalDate fecha2 = LocalDate.parse(fechaStr2, formatter);      
                
                System.out.println(fecha);
                System.out.println(fecha2);
                
                java.sql.Date fechainisql = java.sql.Date.valueOf(fecha);
                java.sql.Date fechafinsql = java.sql.Date.valueOf(fecha2);
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/usersdb", "root", "12345678");       
                String insertQuery = "INSERT INTO eventos (nombre_evento, descripcion_evento, categoria_evento, fechainicio,  fechafin) VALUES (?, ?, ?, ?, ?)";                
                PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
                preparedStatement.setString(1, titulo);
                preparedStatement.setString(2, descripcion);
                preparedStatement.setString(3, categoria);
                preparedStatement.setDate(4, fechainisql);
                preparedStatement.setDate(5, fechafinsql);
                preparedStatement.executeUpdate();
               JOptionPane.showMessageDialog(null, "Evento creado con exito");
                connection.close();
        
        } catch(SQLException e){
             System.err.println("SQL error: " + e.getMessage()); // Print SQL errors
        } catch(ClassNotFoundException ex){
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println("Class not found error: " + ex.getMessage());
        } catch (DateTimeParseException e) {
    // Handle parsing exception if the format doesn't match
    System.err.println("Invalid date format: " + e.getMessage());
}
    }//GEN-LAST:event_createEventMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgapp_2;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JButton createEvent;
    private com.toedter.calendar.JDateChooser dateend;
    private com.toedter.calendar.JDateChooser dateini;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField title;
    private javax.swing.JButton volverapp;
    // End of variables declaration//GEN-END:variables
}
